# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build & publish Docker image for dev

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Build & Test Node app (CI) for dev]
    types: [completed]
    branches: [dev]

permissions:
  contents: 'read'
  packages: 'write'

jobs:
  build-publish-docker:
    runs-on: ubuntu-latest
    environment: dev
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to GitHub container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Log in to Azure container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.ACR_LOGIN_SERVER  }}
        username: ${{ secrets.ACR_USERNAME  }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Lowercase the repo name
      run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

    - name: Build and push container image to GitHub/Azure registry
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: |
          ghcr.io/${{ env.REPO }}-${{ github.ref_name }}:latest
          pfaregistry.azurecr.io/${{ env.REPO }}-${{ github.ref_name }}:latest
        file: ./Dockerfile

    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }} 
        dns-name-label: url-for-container
        image: pfaregistry.azurecr.io/${{ env.REPO }}-${{ github.ref_name }}:latest
        registry-login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        registry-username: ${{ secrets.ACR_USERNAME }}
        registry-password: ${{ secrets.ACR_PASSWORD }}
        name: pfa-discord-bot-container
        secure-environment-variables: |
          DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}
          OPENAI_KEY=${{ secrets.OPENAI_KEY }}
          OPENAI_ORG=${{ secrets.OPENAI_ORG }}
        location: 'northeurope'