# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build & publish Docker image for dev

on:
  workflow_run:
    workflows: [Build & Test Node app (CI) for dev]
    types: [completed]
    branches: [dev]

permissions:
  contents: 'read'
  packages: 'write'

jobs:
  build-publish-docker:
    runs-on: ubuntu-latest
    environment: dev
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Lowercase the repo name
      run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ghcr.io/${{ env.REPO }}-${{ github.ref_name }}:latest
        file: ./Dockerfile