# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs.

name: Node.js CI Hamdi

on:
  push:
    branches: [ "hamdi" ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    environment: hamdi

    steps:
    - name: copy code
      uses: actions/checkout@v3
    - name: Use Node.js (18)
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - run: npm install
    - run: npm ci
    - env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          OPENAI_ORG: ${{ secrets.OPENAI_ORG }}
      run: npm test
      
  docker:  

    runs-on: ubuntu-latest
    environment: haitham
    needs: build
    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo ${{ secrets.DOCKERPW }} | docker login -u ${{ secrets.DOCKERUSER }} --password-stdin
        docker image build -t hamdiing/discord-bot:latest .
        docker push hamdiing/discord-bot:latest

