# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build & Test Node app (CI) for dev

on:
  workflow_dispatch:
  push:
    branches: [ "dev", "gpt-3.5-model" ]
    paths:
      - '**.js'
      - '**.json'
      - '**.yml'
      - 'Dockerfile'

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_test_node:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js (18)
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - run: npm install
    - name: Clean install
      run: npm ci
    - name: Run tests
      env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          OPENAI_ORG: ${{ secrets.OPENAI_ORG }}
      run: npm test
