# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI Hamdi

on:
  push:
    branches: [ "hamdi" ]

jobs:
  build:
  
    runs-on: ubuntu-latest


    steps:
    - name: copy code
      uses: actions/checkout@v3
    - name: Use Node.js (18)
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - run: npm install
    - run: npm ci
    - run: npm test
